### ISSUE TITLE
CSS inspection highlights standard properties as invalid

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-css#4]
```
.ingrid_button
{
    background-image: url("/img/dico/dico_dots.gif");
    background-repeat: no-repeat;
    cursor: pointer;
    display: block;
    height: 16px;
    width: 16px;
    z-index: 1999;
    position: absolute;
    top: 0;
    right: 0;
}
````

![изображение](https://user-images.githubusercontent.com/16825982/84624387-f76dc280-aee9-11ea-9388-8dbcf51d8ec5.png)

**Comment by VISTALL** [comment]
Hello. Yeah css miss many properties. I will add when i have free time

**Comment by unv-unv** [comment]
Any news? Can I help somehow?

**Comment by VISTALL** [comment]
Hello. I delayed this issue - i'm searching right way how impl that. 

I have "strange" css table https://github.com/consulo/consulo-css/blob/master/consulo-xstylesheet/src/main/resources/consulo/xstylesheet/defaultXStyleSheetTable.xml

I wanna rewrite it - make it more clear, and more understandable. I tried import from Netbeans - but too complex.

Also i want parse this page (https://www.w3schools.com/cssref/default.asp). But problem - it's parse property values.

As compromise you can add to  defaultXStyleSheetTable.xml new items, but i'm not sure about adding all items to those file.

**Comment by unv-unv** [comment]
What do you need as a result of parsing? For example, excel file with property name in the first column and property values in the second column? Or some other format?

**Comment by VISTALL** [comment]
> What do you need as a result of parsing? For example, excel file with property name in the first column and property values in the second column? Or some other format?

I'm already wrote simple parser, but - there a next question how make property grammar understandable and support all cases what we need. Info from w3schools.com simplified and not full

CSSwg grammar too complex, but i think need impl it(https://drafts.csswg.org/css-backgrounds-3/#box-shadow)

<shadow> = <color>? && [<length>{2} <length [0,∞]>? <length>?] && inset?

Same here 

https://developer.mozilla.org/ru/docs/Web/CSS/box-shadow

I'm not found all grammars in one file, and it's a problem.

**Comment by VISTALL** [comment]
I added compromise for this issue. I created list with *unknown* properties. They will show in completion, and will not provide inspection problems - but body of those properties will be not validated too.

**Comment by VISTALL** [comment]
to https://github.com/consulo/consulo-css/issues/9
