### ISSUE TITLE
Need support for keyword values of CSS properties cursor, display, position, etc.

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-css#6]
![image](https://user-images.githubusercontent.com/16825982/118211145-56c6b080-b474-11eb-8542-7741d4bd7e44.png)

See list of keywords in:
https://developer.mozilla.org/ru/docs/Web/CSS/cursor
https://developer.mozilla.org/ru/docs/Web/CSS/display
https://developer.mozilla.org/ru/docs/Web/CSS/position

**Comment by VISTALL** [comment]
to https://github.com/consulo/consulo-css/issues/9

**Comment by unv-unv** [comment]
In consulo.css version 3470 I see that "position" property has keywords. But it doesn't have keyword "sticky" (floating withing scroll parent while scrolling). See https://developer.mozilla.org/ru/docs/Web/CSS/position

Properties "cursor" and "display" still have no keywords.

**Comment by VISTALL** [comment]
```css
/* Keyword value */
cursor: pointer;
cursor: auto;

/* URL, with a keyword fallback */
cursor: url(hand.cur), pointer;

/* URL and coordinates, with a keyword fallback */
cursor: url(cursor1.png) 4 12, auto;
cursor: url(cursor2.png) 2 2, pointer;

/* Global values */
cursor: inherit;
cursor: initial;
cursor: unset;
```

also

```
/* <display-listitem> values */
display: list-item;
display: list-item block;
display: list-item inline;
display: list-item flow;
display: list-item flow-root;
display: list-item block flow;
display: list-item block flow-root;
display: flow list-item block;
```

float elements. I can impl single items, but with two elements will be error. I don't want create false errors which I known. Without table - where no errors in any cases.
