### ISSUE TITLE
Property border-color is not highlighted

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-css#7]
![изображение](https://user-images.githubusercontent.com/16825982/118225853-85518500-b48e-11eb-9eab-fe62c328f8ee.png)

**Comment by VISTALL** [comment]
to https://github.com/consulo/consulo-css/issues/9

**Comment by unv-unv** [comment]
Tested in consulo.css version 3470. Still see no highlighting for "border-color" property value.
